### ISSUE TITLE
Pinout documentation

### ISSUE THREAD

**Issue by dani-carbonell** [mufpga/MicroMojo#2]
I just realized the pinout was updated in June and but not the wiki documentation. I dont know how to edit it.
I have some questions about this change:

1. What was the reason for this update?
2. Why this zigzag pattern in the pin assignment?
3. Do you think is a good idea to link the wiki "wiring" page to the pinout table?

**Comment by jdeschamps** [comment]
Hi Dani!

**1) and 2)** I updated it because when putting together a compact electronics box with the mojo, I did not have space to insert the pins (I cut the pins from rows of pins, it is quite dirty and they end up not fitting next to each other). Hence the zig-zag pattern.

I then updated the repository with what I actually used on our microscopes. Mostly for my coworkers, if they ever have a look at it when debugging something.

I encountered problems once the mojo was all wired with the microscope (for instance the sequenced triggering does not work anymore, although no trigger is lost). Maybe interferences between the cables and nearby pins? Your idea of a Mojo shield (I think we discussed this in the pas), would probably solve this...

**3)** Absolutely. However, since the Mojo is outdated, I don't see much use in spending time on finishing the wiki... The plan currently is by the of January to have the updated code for the Alchitry Au and Cu FPGAs. Then, I will remove the wiki pages (I am not a fan of those) and then do a markdown documentation (like [for the laser engine](https://github.com/ries-lab/LaserEngine)) and maybe even a github.io (like [for EMU](https://jdeschamps.github.io/EMU-guide/)).

**Comment by dani-carbonell** [comment]
Hi Joran!
I think we are still going to make the shields for the Mojo because its what we already have here and the dessign could be also ported to the new alquitry boards (change the footprint and the connectors but keep the components). We plan to manufacture our PCB with jlcpcb.com witch is incredible cheap (2$) and solder the components in my workshop. I think we are going to stay with the old pinout for now. 

I have to say that the work you did documenting the laser engine is beautiful, really impresive. So yeah, I also prefer the Markdown over the Wiki :)

**Comment by jdeschamps** [comment]
Thanks!

Let's get in touch again by email regarding the shield, especially if the connectors are compatible with the Alchitry Au and that we can put this on the repository.

I'll close the issue now!
